/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.uniba.thesis;

import java.util.ArrayList;
import java.util.List;

import org.chocosolver.solver.Model;
import org.chocosolver.solver.variables.IntVar;
import org.chocosolver.solver.Solver;
import org.chocosolver.solver.search.strategy.Search;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public void doSomeCSP() {
        // 1. Create a Model
        Model model = new Model("my first problem");
        // 2. Create variables
        int min = 0;
        int max = 100;
        Interval load = new Interval("load", model, min, max, 5);
        Interval move = new Interval("move", model, min, max, 20);
        Interval inspect = new Interval("inspect", model, min, max, 5);
        Interval unload = new Interval("unload", model, min, max, 5);
        Interval seal = new Interval("seal", model, min, max, 2);
        // 3b. Or directly through variables
        load.before(move).post();
        seal.before(move).post();
        move.before(unload).post();
        load.before(seal).post();
        inspect.before(move).post();
        seal.before(unload).post();
        model.or(inspect.before(load), inspect.after(load)).post();
        model.or(seal.before(move), seal.after(move)).post();
        // 
        List<IntVar> vars = new ArrayList<>();
        vars.addAll(load.getVars());
        vars.addAll(move.getVars());
        vars.addAll(inspect.getVars());
        vars.addAll(unload.getVars());
        vars.addAll(seal.getVars());
        
        // 4. Get the solver
        Solver solver = model.getSolver();
        // 5. Define the search strategy
        solver.setSearch(Search.minDomLBSearch(vars.toArray(new IntVar[vars.size()])));
        // 6. Launch the resolution process
        solver.solve();
        // 7. Print search statistics
        solver.printStatistics();
        System.out.println(load);
        System.out.println(move);
        System.out.println(inspect);
        System.out.println(unload);
        System.out.println(seal);
    }

    public static void main(String[] args) {
        new App().doSomeCSP();
    }
}
